### PR TITLE
Refactored Packets for replica request and Replica Manager requests a…

### PR DESCRIPTION
**Pull request by cclp94**
…nd replies. Created Replica operation replies.

### CODE REVIEW

**Review by Mack-Lee — COMMENTED** [review]
You refactored "ReplicaOperation" to just "Operation?
Also, the "getByteArray()" method was removed from the Packet class - I suppose it will not be used?

**Review by Mack-Lee — APPROVED** [review]
These packets are sent to the FE to be parsed there, right? Approved per your request.

**Comment by cclp94** [comment]
Yeah... So the idea is to have everything Inheriting from OperationParamenters, that includes the replica and  RM operations that are now defined in the Operation enum. So everything can be sent as a Packet instead of other types like ReplicaManagerPacket. It makes it easier to parse everything when getting it back in the FE

**Comment by cclp94** [comment]
As for the getByteArray, we are using the UdpHelper class now

**Pull request merged**
